
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GET_MOVES_COUNT = 51;
  public static final int LBRACKET = 40;
  public static final int RANDOM = 45;
  public static final int WITH = 12;
  public static final int GE = 32;
  public static final int MUTUAL = 17;
  public static final int REWARD = 21;
  public static final int SCORING = 10;
  public static final int LPAREN = 38;
  public static final int DEFECTION = 19;
  public static final int MATCH = 3;
  public static final int RULES = 6;
  public static final int RPAREN = 39;
  public static final int D = 24;
  public static final int C = 23;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int INTLIT = 53;
  public static final int GET_LAST_N_MOVES = 52;
  public static final int LT = 35;
  public static final int OR = 28;
  public static final int COMMA = 43;
  public static final int STRATEGIES = 15;
  public static final int MAIN = 4;
  public static final int IF = 7;
  public static final int ID = 55;
  public static final int LE = 33;
  public static final int INITIAL = 5;
  public static final int EOF = 0;
  public static final int ROUNDS = 16;
  public static final int RBRACKET = 41;
  public static final int PUNISHMENT = 22;
  public static final int TRUE = 25;
  public static final int error = 1;
  public static final int PLAYERS = 14;
  public static final int TOTAL_ROUNDS = 46;
  public static final int NEQ = 31;
  public static final int BETRAYAL = 20;
  public static final int FLOATLIT = 54;
  public static final int EQ = 30;
  public static final int STRATEGY = 2;
  public static final int SELF_HISTORY = 48;
  public static final int ROUND_NUMBER = 44;
  public static final int COLON = 42;
  public static final int LAST_MOVE = 50;
  public static final int COOPERATION = 18;
  public static final int LBRACE = 36;
  public static final int ELSE = 9;
  public static final int GET_MOVE = 49;
  public static final int RBRACE = 37;
  public static final int THEN = 8;
  public static final int SEED = 13;
  public static final int OPPONENT_HISTORY = 47;
  public static final int FALSE = 26;
  public static final int RUN = 11;
  public static final int GT = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRATEGY",
  "MATCH",
  "MAIN",
  "INITIAL",
  "RULES",
  "IF",
  "THEN",
  "ELSE",
  "SCORING",
  "RUN",
  "WITH",
  "SEED",
  "PLAYERS",
  "STRATEGIES",
  "ROUNDS",
  "MUTUAL",
  "COOPERATION",
  "DEFECTION",
  "BETRAYAL",
  "REWARD",
  "PUNISHMENT",
  "C",
  "D",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "NEQ",
  "GE",
  "LE",
  "GT",
  "LT",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "COMMA",
  "ROUND_NUMBER",
  "RANDOM",
  "TOTAL_ROUNDS",
  "OPPONENT_HISTORY",
  "SELF_HISTORY",
  "GET_MOVE",
  "LAST_MOVE",
  "GET_MOVES_COUNT",
  "GET_LAST_N_MOVES",
  "INTLIT",
  "FLOATLIT",
  "ID"
  };
}

